[package]
name = "better-tree"
version = "0.1.0"
edition = "2021"
about = "Better `tree` command."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
colored = "2"
getopts = "*"
